version: '3.3'
services:
  php-fpm:
    build: ./data/php/
    volumes:
      - ./data/app:/data/app
    links:
      - mysql
    working_dir: /data/app/blog
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=laravel
  nginx:
    image: nginx
    volumes:
      - ./data/app:/data/app
      - ./data/nginx/my.conf:/etc/nginx/conf.d/my.conf
    ports:
      - "5000:80"
    links:
      - php-fpm